/**
 * Customer-related types
 */

import { CustomerId } from '../evolu/evolu-db';

/**
 * Sex options for customer profiles
 */
export type Sex = 'male' | 'female' | 'other';

/**
 * Customer representation for UI display and business logic
 *
 * Note: createdAt, updatedAt, isDeleted, and ownerId are automatically
 * managed by Evolu and do not need to be included in this interface.
 */
export interface Customer {
    /** Unique customer identifier from Evolu database */
    id: CustomerId;
    /** Customer's first name */
    firstName?: string;
    /** Customer's last name */
    lastName?: string;
    /** Academic or professional degree/title (free-text, max 10 characters recommended) */
    degree?: string;
    /** Customer's date of birth */
    birthDate?: Date;
    /** Whether the customer is an adult (18+) */
    isAdult?: boolean;
    /** Customer's sex */
    sex?: Sex;
    /** External customer identifier (for integration with other systems) */
    customerId?: string;
}

/**
 * Form data for creating or updating a customer
 * Excludes the id field since it's generated by the database
 */
export interface CustomerFormData {
    /** Customer's first name */
    firstName?: string;
    /** Customer's last name */
    lastName?: string;
    /** Academic or professional degree/title (free-text, max 10 characters recommended) */
    degree?: string;
    /** Customer's date of birth */
    birthDate?: Date;
    /** Whether the customer is an adult (18+) */
    isAdult: boolean;
    /** Customer's sex */
    sex?: Sex;
    /** External customer identifier (for integration with other systems) */
    customerId?: string;
}
